name: Build and push

on: [push]

jobs:

  clojure:

    # strategy:
    #   matrix:
    #     os: [ubuntu-latest, macOS-latest, windows-latest]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1
      - run: aws --version
        shell: bash

      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@3.5
        with:
          # Install just one or all simultaneously
          cli: 1.10.1.693 # Clojure CLI based on tools.deps
          lein: 2.9.1     # or use 'latest' to always provision latest version of leiningen

      - name: Run test suite
        run: lein doo phantom test once

      - name: Lein build
        run: lein build

      # - name: Lein build
      #   run: lein cljsbuild once min

      - name: Deploy
        env:
          AWS_ACCESS_TOKEN: ${{ secrets.AWS_ACCESS_TOKEN }}
          AWS_SECRET_TOKEN: ${{ secrets.AWS_SECRET_TOKEN }}
        run: aws s3 sync resources/public/ s3://envoys-frontend
