name: Build and push

on: [push]

jobs:

  clojure:

    # strategy:
    #   matrix:
    #     os: [ubuntu-latest, macOS-latest, windows-latest]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1

      - run: aws --version
        shell: bash

      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@3.5
        with:
          # Install just one or all simultaneously
          cli: 1.10.1.693 # Clojure CLI based on tools.deps
          lein: 2.9.1     # or use 'latest' to always provision latest version of leiningen

      - name: Run test suite
        run: lein doo phantom test once

      # - name: Lein build
      #   run: lein build

      - name: Lein build
        run: lein cljsbuild once min

      - name: Deploy
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks # --debug
        env:
          AWS_S3_BUCKET: 'envoys-frontend' # ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_TOKEN }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_TOKEN }}
          AWS_REGION: 'eu-west-1'   # optional: defaults to us-east-1
          SOURCE_DIR: 'resources/public/'      # optional: defaults to entire repository

      - name: Invalidate cloudfront cache
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_TOKEN }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_TOKEN }}
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRO }} --paths "/*"
